### ISSUE TITLE
update for hawthorn.1

### ISSUE THREAD

**Issue by cequn** [Stanford-Online/xblock-in-video-quiz#17]
The current version works for ginkgo, when will you update it for hawthorn?

**Comment by stvstnfrd** [comment]
@cequn Can you provide some additional information? Your mention implies that it doesn't currently work on hawthorn; what issues are you encountering?

**Comment by cequn** [comment]
@stvstnfrd sorry for later reply, I think i figure it out, but i can't remember what it is, it seems the issue of django version, hawthorn use a django>1.9,
