### ISSUE TITLE
Fine logs but nothing happens

### ISSUE THREAD

**Issue by eazaika** [Stanford-Online/xblock-in-video-quiz#22]
XBlock==1.2.1
xblock-utils==1.2.0
edx-opaque-keys==0.4.4
Install invideoquiz at hawthorn.2, reboot services and recompile statics (js etc.)
In Studio xblock is perfect (found video by video_id, read problem timemap) BUT in LMS:
1. over multiple choice problem it signs:
> This component will appear in the video at 0:10

**_looks good_**

2. starts video and after 10 seconds nothing happens! **_bad behaviour_**
in the console.log no one error 
/edx/var/log/supervisor/[l|c]ms-stderr.log is empty from errors too

What's the problem?

**Comment by eazaika** [comment]
Okay, problem is solved: by staff profile don't woks. By ordinar student works fine

**Comment by abstract-technology** [comment]
Hi, we are testing and trying to understand how this pluging works, the Javascript breaks down and the XBlocks no longer render. Could you tell us, if it has already been tested in Koa?
