### ISSUE TITLE
I am currently getting an error when I installed this Xblock on the AsideUsageKeyV2

### ISSUE THREAD

**Issue by joshoftenly** [Stanford-Online/xblock-in-video-quiz#24]
ImportError: cannot import name AsideUsageKeyV2

This error persisted after using pip unistall.

**Comment by joshoftenly** [comment]
updating the Opaque keys (from github) to the correct version solved this. (You have to match the update to what the error will tell you it needs). 

IE look at the error logs and read them until you understand them. 

Also, geez it'd be helpful if you open source folks would update your packages :)

**Comment by sumeshiit** [comment]
@joshoftenly  . we getting this issue, after installing this xblock in ironwood version. currently the lms & cms is not starting. could you please help us to resolve this issue. if possible, please share the steps and the commands you followed to fix this issue.

**Comment by joshoftenly** [comment]
Yeah if the LMS and CMS aren't starting there are a number of things that can be the problem. Usually it means there's an error in either the lms.env.json, cms.env.json file. Which will cause that.
