### ISSUE TITLE
please provide more instruction for studio

### ISSUE THREAD

**Issue by JustinPringle** [Stanford-Online/xblock-in-video-quiz#26]
Firstly thanks for developing this!
I have "successfully" installed the xblock but it seems to be silently failing in that no questions are showing up at the desired timestep

I would like to check that I am using correct kindly advise on the following:

1. Dose it matter where I "put" the problem i.e. should I create a new unit for it or can it sit under the video?
2. What is the video ID? Is it the full string: "block-v1+...." or is it just the random number? Also do I need to use inverted commas when inputting this?
3. What is the problem ID in the problem timemap field? Again is it the full "block-v1..." or just the random number?
<img width="977" alt="Screenshot 2020-06-11 at 09 35 55" src="https://user-images.githubusercontent.com/26479976/84358142-ffb2be80-abc6-11ea-8701-a030b0ad08ae.png">

**Comment by busi-reddy-karnati** [comment]
May I please ask you @JustinPringle how you have added the Xblock. I have installed the Xblock and pip installed requirements.txt. I have changed the advance modules to ["invideoquiz"]. The advance button doesn't show up. Any idea what's wrong? Thanks .

**Comment by stvstnfrd** [comment]
Following the sunset of the Lagunita project, this repo lives on under edx's stewardship at:
- https://github.com/edx/xblock-in-video-quiz

Assuming you're running a relatively recent version of edx-platform (>= hawthorn), you'll want to install the edx version of this.

Sorry for the confusion.
