### ISSUE TITLE
Problems no longer showing up inside video components as intended 

### ISSUE THREAD

**Issue by llewenstein** [Stanford-Online/xblock-in-video-quiz#29]
Hello!

1) I am a member of the edx.org support team and a course team from Stanford has flagged that the quiz is not showing up inside the video as it is supposed to be. I am not personally sure what the expected behavior is/was. However, I can confirm that after enabling this feature and filling out the required settings that the component never shows up inside the video in MFE and in legacy. Please see pictures attached.

*Based on this issue (https://github.com/Stanford-Online/xblock-in-video-quiz/issues/22), I am assuming that this tool still works in legacy while enrolled as a learner but edx.org no longer allows learners to view this content in legacy - only in MFE.  

![Screen Shot 2021-07-06 at 8 55 31 PM](https://user-images.githubusercontent.com/67072639/124684654-a5556180-de9d-11eb-9f03-75e86c3fcea8.png)
![Screen Shot 2021-07-06 at 8 55 47 PM](https://user-images.githubusercontent.com/67072639/124684655-a5556180-de9d-11eb-9cc0-b45d3f19a7a5.png)

2) Also, the bar that states "This component will appear in the video at 1:00" at the top of each problem component in the instructor view no longer appears when viewing the course in MFE (https://learning.edx.org/...). It is only visible in legacy(https://courses.edx.org/...). Please see pictures attached. 

![Screen Shot 2021-07-06 at 9 04 58 PM](https://user-images.githubusercontent.com/67072639/124684796-f2393800-de9d-11eb-8700-e7ec1b858de3.png)
![Screen Shot 2021-07-06 at 9 05 27 PM](https://user-images.githubusercontent.com/67072639/124684797-f2393800-de9d-11eb-90a6-82ff2b263764.png)

3) It also seems as though the problem components should be hidden from learners. However, when viewing the course as a learner in MFE I can see the problem components below the video. Please see picture attached. 

![Screen Shot 2021-07-06 at 9 00 34 PM](https://user-images.githubusercontent.com/67072639/124684657-a5edf800-de9d-11eb-843a-ecefe2519a2a.png)
^Note that this is from a test account where I enrolled directly into this course as an ordinary learner. 

View of console while viewing MFE in test account:
![Screen Shot 2021-07-06 at 9 39 08 PM](https://user-images.githubusercontent.com/67072639/124687371-bfde0980-dea2-11eb-992e-de10b5362ddc.png)

![Screen Shot 2021-07-06 at 9 02 12 PM](https://user-images.githubusercontent.com/67072639/124684659-a5edf800-de9d-11eb-94ef-95971849b20e.png)
^Note that I am unable to test this tool as an average learner in legacy

Thank you!

**Comment by abstract-technology** [comment]
Hi, we are testing and trying to understand how this pluging works, the Javascript breaks down and the XBlocks no longer render. Could you tell us, if it has already been tested in Koa?

**Comment by tatamu-fold** [comment]
Video ID is actually the component ID for the video in which you want to insert your quiz questions. It can be obtained from staff debug info of the video in the LMS. @llewenstein

**Comment by stvstnfrd** [comment]
Hi everyone! As an FYI, this XBlock, while originally developed by Stanford, is now "owned" by edx.
Issues should be directed here: https://github.com/edx/xblock-in-video-quiz/issues

The scope of this issue was that the XBlock stopped working inside the new Learning MFE used by edx.org .
It was still working in the original, legacy Courseware experience.

That all said, this should now work in the MFE as well, following https://github.com/edx/xblock-in-video-quiz/pull/22

Thanks!
